### PR TITLE
+ writePoints method matching node-influx implementation

### PR DESCRIPTION
**Pull request by anfedorov**
Implementation of writePoints with the same interface as in
node-influx: https://github.com/node-influx/node-influx#writepoints

### CODE REVIEW

**Comment by panda-moe-zz** [comment]
Waiting for this to be merged!

**Comment by freshlogic** [comment]
@anfedorov would you be up for becoming a contributor to this project?

**Comment by anfedorov** [comment]
absolutely!

**Comment by anfedorov** [comment]
merged via cli

**Pull request closed without merging**
