### PR TITLE
fix and test lineProtocol, close socket

### PR DESCRIPTION
**Pull request by anfedorov**
- fix line protocol implementation
- add tests for JSON and line protocols
- close socket on send so that node exits process

### CODE REVIEW

**Comment by Harrison-M** [comment]
Do you have a use case for `convertPointToLine` or the similar functions being publicly available? I'd prefer to keep the utility functions private unless there's a good reason to make them part of the public API.

**Comment by anfedorov** [comment]
good call. fixed.

**Comment by anfedorov** [comment]
@Harrison-M any objections to my merging this? sounds like some folks are waiting on it and #5

**Comment by freshlogic** [comment]
Go for it. Once you have a new version ready we can add you to NPM so you can publish

**Pull request merged**
