### PR TITLE
2.0.0

### PR DESCRIPTION
**Pull request by anfedorov**
- add support for InfluxDB 0.9
- conform to same API as node-influx lib
- add UDP support
- add tests, eslint, travis, and coveralls

### CODE REVIEW

**Comment by anfedorov** [comment]
let's aim to merge by tomorrow night? I want to go over everything once more because it's been awhile since I thought about this code

**Comment by freshlogic** [comment]
@anfedorov looking good to me. glad to have travis ci, eslint, and coveralls setup. merge when ready and we'll publish to npm over at https://www.npmjs.com/package/influx-udp

**Comment by anfedorov** [comment]
ok lgtm.

since this is backwards compatible, based on [semver](http://semver.org/), calling it 2.0.0 is probably too ambitious. it might be worthwhile just to version it with whatever influxdb version it is tested against.

I got data sending to 1.3.5 just now, but I'm not sure whether json is still supported or if this documentation is up to date. merging so folks can start using it and I'll update that when I get the chance.

**Comment by freshlogic** [comment]
@anfedorov I went ahead and published v1.1.0 to NPM: https://www.npmjs.com/package/influx-udp

Do you have an NPM username I can add as an owner so you can do the next one?

**Comment by anfedorov** [comment]
Yup, anfedorov there, as well: https://npmjs.com/~anfedorov

**Comment by freshlogic** [comment]
```
$ npm owner add anfedorov
+ anfedorov (influx-udp)
```

**Pull request merged**
